### ISSUE TITLE
AG how do i get barrel textuers

### ISSUE THREAD

**Issue by Ozi6** [AnotherGuy7/Dungeon-Adventure-Gang#1]
AG pleas help i cant make barrel man like this

**Comment by Ozi6** [comment]
wait are these not to use EXTREMELY URGENT bug report threads and super official things i dont know what issues are

**Comment by AnotherGuy7** [comment]
> wait are these not to use EXTREMELY URGENT bug report threads and super official things i dont know what issues are

They have to do with bugs in the code.
